/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulceria;

import dulceria.clases.Dulce;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kledioz
 */
public class Borrar extends javax.swing.JFrame {

    Opciones op;

    /**
     * Creates new form Seleccionar
     */
    public Borrar(Opciones op) {
        this.op = op;
        initComponents();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                op.setEnabled(true);
                dispose();
            }
        });

        op.setEnabled(false);

        DefaultTableModel modelo = (DefaultTableModel) tbl_borrar.getModel();
        modelo.setRowCount(0);

        Object[][] lista = new Object[35][2];

        int i = 0;

        for (Dulce dul : op.main.dulces) {

            double info = 0;

            info = dul.getCodigo();

            lista[i][0] = info;
            lista[i][1] = dul;
            i++;
        }

        op.main.quickSort(lista, 0, i - 1, true);

        for (int j = 0; j < lista.length; j++) {
            Dulce dul = (Dulce) lista[j][1];
            if (dul == null) {
                break;
            }
            modelo.addRow(new Object[]{dul.getCodigo(), dul.getNombre(), dul.getCantidad(), dul.getPrecio(), dul.getCategoria()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_borrar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_regresar_borrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dulceria | Borrar");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(501, 500));
        setMinimumSize(new java.awt.Dimension(501, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        tbl_borrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_borrar.setColumnSelectionAllowed(true);
        tbl_borrar.getTableHeader().setReorderingAllowed(false);
        tbl_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_borrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_borrar);
        tbl_borrar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 500, 460);

        jLabel1.setText("Selecciona el producto a borrar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(155, 15, 179, 16);

        btn_regresar_borrar.setText("Regresar");
        btn_regresar_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresar_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar_borrar);
        btn_regresar_borrar.setBounds(413, 11, 83, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ab.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-60, -800, 600, 1380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresar_borrarActionPerformed
        op.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresar_borrarActionPerformed

    private void tbl_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_borrarMouseClicked
        if (tbl_borrar.getSelectedRow() != -1) {
            int codigo = (int) tbl_borrar.getValueAt(tbl_borrar.getSelectedRow(), 0);

            for (Dulce dd : op.main.dulces) {
                if (dd.getCodigo() == codigo) {
                    op.main.dulces.remove(dd);
                    op.setEnabled(true);
                    JOptionPane.showMessageDialog(this, "Se ha borrado el producto \"" + dd.getNombre() + "\" exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    break;
                }
            }

        }
    }//GEN-LAST:event_tbl_borrarMouseClicked
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/borrar.png"));

        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar_borrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_borrar;
    // End of variables declaration//GEN-END:variables
}
