/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulceria;

import dulceria.clases.Dulce;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kledioz
 */
public class Edicion extends javax.swing.JFrame {

    Opciones op;
    Dulce edicion = null;
    

    public Edicion(Opciones op, Dulce edicion) {
        this.op = op;
        this.edicion = edicion;
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                op.setEnabled(true);
                dispose();
            }
        });

        if (edicion != null) {

            txtCodigo.setText(edicion.getCodigo() + "");
            txt_codigo.setText(edicion.getNombre());
            txt_cantidad.setText(edicion.getCantidad() + "");
            txt_precio.setText(edicion.getPrecio() + "");
            box_categoria.setSelectedItem(edicion.getCategoria());

            txtCodigo.setEnabled(false);
            txt_codigo.setEnabled(false);
            box_categoria.setEnabled(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btn_ok_edicion = new javax.swing.JButton();
        btn_cancelar_edicion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        box_categoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informacion del producto");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(300, 230));
        setPreferredSize(new java.awt.Dimension(300, 250));
        setResizable(false);

        jLabel1.setText("Codigo");

        jLabel2.setText("Precio");

        jLabel3.setText("Nombre");

        jLabel4.setText("Cantidad");

        txtCodigo.setMaximumSize(new java.awt.Dimension(200, 24));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txt_codigo.setMaximumSize(new java.awt.Dimension(200, 24));

        txt_precio.setMaximumSize(new java.awt.Dimension(200, 24));

        txt_cantidad.setToolTipText("");
        txt_cantidad.setMaximumSize(new java.awt.Dimension(200, 24));

        btn_ok_edicion.setText("OK");
        btn_ok_edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_edicionActionPerformed(evt);
            }
        });

        btn_cancelar_edicion.setText("Cancelar");
        btn_cancelar_edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_edicionActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoria");

        box_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dulce", "Salado", "Enchiloso" }));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_ok_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_cancelar_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(box_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btn_ok_edicion))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btn_cancelar_edicion))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(70, 70, 70)
                .addComponent(box_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed


    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btn_ok_edicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_edicionActionPerformed

        if (txtCodigo.getText().length() != 0
                && txt_codigo.getText().length() != 0
                && txt_precio.getText().length() != 0
                && txt_cantidad.getText().length() != 0) {

            int codigo = 0;
            int cantidad = 0;
            double precio = 0;

            try {
                codigo = Integer.valueOf(txtCodigo.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Debes introducir un numero valido en Codigo", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                cantidad = Integer.valueOf(txt_cantidad.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Debes introducir un numero valido en Cantidad", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                precio = Double.valueOf(txt_precio.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Debes introducir un numero valido en Precio", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (edicion == null) {
                for (Dulce d : op.main.dulces) {
                    if (d.getCodigo() == codigo) {
                        JOptionPane.showMessageDialog(this, "Ya hay un producto con el mismo codigo", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    if (d.getNombre().toLowerCase().equals(txt_codigo.getText().toLowerCase())) {
                        JOptionPane.showMessageDialog(this, "Ya hay un producto con el mismo nombre", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                }
                edicion = new Dulce();
                op.main.dulces.add(edicion);
                edicion.setCodigo(codigo);
                edicion.setNombre(txt_codigo.getText());
                edicion.setCategoria((String) box_categoria.getSelectedItem());
                JOptionPane.showMessageDialog(this, "Se ha ingresado el producto \"" + txt_codigo.getText() + "\" exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Se ha modificado el producto \"" + txt_codigo.getText() + "\" exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }

            edicion.setCantidad(cantidad);
            edicion.setPrecio(precio);

            op.setEnabled(true);
            op.actualizarEstadisticas();
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_ok_edicionActionPerformed

    private void btn_cancelar_edicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_edicionActionPerformed
        op.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelar_edicionActionPerformed
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/editar.png"));


        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box_categoria;
    private javax.swing.JButton btn_cancelar_edicion;
    private javax.swing.JButton btn_ok_edicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
