/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulceria;

import dulceria.clases.Dulce;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author Kledioz
 */
public class Main extends javax.swing.JFrame {

    //Variables
    public static ArrayList<Dulce> dulces = new ArrayList<>();

    //Estadisticas
    public int productosComprados = 0;
    public double dineroGanado = 0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dulceria Mundo de Caramelo");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(508, 530));
        setMinimumSize(new java.awt.Dimension(508, 530));
        setPreferredSize(new java.awt.Dimension(508, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Copyright © 2019 by Claudio B. Alfonso S. Marco E. Eden M.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 470, 420, 20);

        btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/puerta.png"))); // NOI18N
        btn_entrar.setBorderPainted(false);
        btn_entrar.setOpaque(false);
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar);
        btn_entrar.setBounds(70, 290, 110, 110);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        btn_salir.setBorderPainted(false);
        btn_salir.setOpaque(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir);
        btn_salir.setBounds(280, 290, 160, 116);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dulceria.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 40, 290, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rosa.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        Opciones op = new Opciones(this);
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/dulceria.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
   
    public static Object[][] quickSort(Object[][] arreglo, int primero, int ultimo, boolean ascendente) {
        int i = primero;
        int j = ultimo;
        //Obtendremos el pivote que esta en medio entre las 2 posiciones
        double pivote = (double) arreglo[(primero + ultimo) / 2][0];
        //Este ciclo se dejara de ejecutar cuando ambas posiciones (i Y j) se crucen
        do {
            //Estos ciclos determinara desde que posicion se realizara el intercambio
            if (ascendente) {
                while ((double) arreglo[i][0] < pivote) {
                    i++;
                }
                while ((double) arreglo[j][0] > pivote) {
                    j--;
                }
            } else {
                while ((double) arreglo[i][0] > pivote) {
                    i++;
                }
                while ((double) arreglo[j][0] < pivote) {
                    j--;
                }
            }
            //Esta condicion determina si no se han cruzado las posiciones
            //asi para poder realizar el intercambio
            if (i <= j) {
                double temporal = (double) arreglo[j][0];
                Dulce temporaldul = (Dulce) arreglo[j][1];

                arreglo[j][0] = (double) arreglo[i][0];
                arreglo[j][1] = (Dulce) arreglo[i][1];

                arreglo[i][0] = temporal;
                arreglo[i][1] = temporaldul;

                i++;
                j--;
            }
        } while (i <= j);
        //Como el arreglo ya esta separado entre menores y mayores (del pivote)
        //se empezara a ordenar ambas mitades
        if (primero < j) {
            quickSort(arreglo, primero, j, ascendente);
        }
        if (ultimo > i) {
            quickSort(arreglo, i, ultimo, ascendente);
        }
        return arreglo;
    }

}
