/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulceria;

import dulceria.clases.Dulce;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kledioz
 */
public class Seleccionar extends javax.swing.JFrame {

    Opciones op;

    /**
     * Creates new form Seleccionar
     */
    public Seleccionar(Opciones op) {
        this.op = op;
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                op.setEnabled(true);
                dispose();
            }
        });

        op.setEnabled(false);

        DefaultTableModel modelo = (DefaultTableModel) tbl_seleccion.getModel();
        modelo.setRowCount(0);

        Object[][] lista = new Object[35][2];

        int i = 0;

        for (Dulce dul : op.main.dulces) {

            double info = 0;

            info = dul.getCodigo();

            lista[i][0] = info;
            lista[i][1] = dul;
            i++;
        }

        op.main.quickSort(lista, 0, i - 1, true);

        for (int j = 0; j < lista.length; j++) {
            Dulce dul = (Dulce) lista[j][1];
            if (dul == null) {
                break;
            }
            modelo.addRow(new Object[]{dul.getCodigo(), dul.getNombre(), dul.getCantidad(), dul.getPrecio(), dul.getCategoria()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_seleccion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_regresar_seleccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dulceria | Seleccionar");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(564, 460));
        setMinimumSize(new java.awt.Dimension(564, 460));
        setPreferredSize(new java.awt.Dimension(564, 460));
        getContentPane().setLayout(null);

        tbl_seleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_seleccion.setColumnSelectionAllowed(true);
        tbl_seleccion.getTableHeader().setReorderingAllowed(false);
        tbl_seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_seleccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_seleccion);
        tbl_seleccion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 548, 381);

        jLabel1.setText("Selecciona el producto a editar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(205, 15, 176, 16);

        btn_regresar_seleccion.setText("Regresar");
        btn_regresar_seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresar_seleccionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar_seleccion);
        btn_regresar_seleccion.setBounds(461, 11, 83, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vd.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar_seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresar_seleccionActionPerformed
        op.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresar_seleccionActionPerformed

    private void tbl_seleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_seleccionMouseClicked
        if (tbl_seleccion.getSelectedRow() != -1) {
            int codigo = (int) tbl_seleccion.getValueAt(tbl_seleccion.getSelectedRow(), 0);
            for (Dulce dd : op.main.dulces) {
                if (dd.getCodigo() == codigo) {
                    Edicion ed = new Edicion(op, dd);
                    ed.setVisible(true);
                    this.dispose();
                    break;
                }
            }

        }
    }//GEN-LAST:event_tbl_seleccionMouseClicked
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/seleccion.png"));

        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar_seleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_seleccion;
    // End of variables declaration//GEN-END:variables
}
