/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulceria;

import dulceria.clases.Dulce;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kledioz
 */
public class Ventas extends javax.swing.JFrame {

    Opciones op;
    Dulce seleccionado = null;

    /**
     * Creates new form Ventas
     */
    public Ventas(Opciones op) {
        this.op = op;
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                op.setEnabled(true);
                dispose();
            }
        });

        op.setEnabled(false);
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_ventas.getModel();
        modelo.setRowCount(0);

        Object[][] lista = new Object[35][2];

        int i = 0;

        for (Dulce dul : op.main.dulces) {

            double info = 0;

	    info  = dul.getCodigo();

            lista[i][0] = info;
            lista[i][1] = dul;
            i++;
        }

        op.main.quickSort(lista, 0, i - 1, true);

        for (int j = 0; j < lista.length; j++) {
            Dulce dul = (Dulce) lista[j][1];
            if (dul == null) {
                break;
            }
            modelo.addRow(new Object[]{dul.getCodigo(), dul.getNombre(), dul.getCantidad(), dul.getPrecio(), dul.getCategoria()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_cancelar_ventas = new javax.swing.JButton();
        btn_comprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinner_cantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dulceria | Ventas");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(790, 470));
        setMinimumSize(new java.awt.Dimension(790, 470));
        setPreferredSize(new java.awt.Dimension(790, 470));
        getContentPane().setLayout(null);

        tbl_ventas.setBackground(new java.awt.Color(204, 204, 255));
        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ventas.setColumnSelectionAllowed(true);
        tbl_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_ventas.getTableHeader().setReorderingAllowed(false);
        tbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ventasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_ventas);
        tbl_ventas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(13, 10, 490, 410);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        btn_cancelar_ventas.setText("Cancelar");
        btn_cancelar_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_ventasActionPerformed(evt);
            }
        });

        btn_comprar.setText("Comprar");
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Codigo del producto");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del producto");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad disponible");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Precio del producto");

        spinner_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 666, 1));
        spinner_cantidad.setEnabled(false);
        spinner_cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_cantidadStateChanged(evt);
            }
        });
        spinner_cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinner_cantidadMouseClicked(evt);
            }
        });

        jLabel5.setText("Cantidad a comprar");

        jLabel6.setText("Total");

        txtTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTotal.setText("$0.00");

        lblCodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCodigo.setText("-");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNombre.setText("-");

        lblCantidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCantidad.setText("-");

        lblPrecio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblPrecio.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinner_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cancelar_ventas)
                        .addGap(40, 40, 40)
                        .addComponent(btn_comprar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombre))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinner_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar_ventas)
                    .addComponent(btn_comprar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 10, 240, 410);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/az.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-4, -7, 780, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed

        if (seleccionado != null) {
            int cantidad = (int) spinner_cantidad.getModel().getValue();
            double costo = seleccionado.getPrecio() * cantidad;

            seleccionado.setCantidad(seleccionado.getCantidad() - cantidad);
            op.main.dineroGanado += costo;
            op.main.productosComprados += cantidad;

            if (seleccionado.getCantidad() <= 0) {
                op.main.dulces.remove(seleccionado);
            }

            this.dispose();
            op.setEnabled(true);
            op.actualizarEstadisticas();

            JOptionPane.showMessageDialog(this, "Se ha registrado la venta del producto\n\"" + seleccionado.getNombre() + "\"\nCosto: $" + new DecimalFormat("##.##").format(costo) + " ✖ " + cantidad + " unidades", "Exito", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btn_comprarActionPerformed

    private void tbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ventasMouseClicked
        if (tbl_ventas.getSelectedRow() != -1) {
            int codigo = (int) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 0);
            for (Dulce dd : op.main.dulces) {
                if (dd.getCodigo() == codigo) {
                    seleccionado = dd;
                    break;
                }
            }

            lblCodigo.setText(seleccionado.getCodigo() + "");
            lblNombre.setText(seleccionado.getNombre());
            lblPrecio.setText(seleccionado.getPrecio() + "");
            lblCantidad.setText(seleccionado.getCantidad() + "");
            spinner_cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, seleccionado.getCantidad(), 1));
            JFormattedTextField tf = ((JSpinner.DefaultEditor) spinner_cantidad.getEditor()).getTextField();
            tf.setEditable(false);
            spinner_cantidad.setEnabled(true);

            txtTotal.setText("$" + new DecimalFormat("##.##").format(seleccionado.getPrecio()));
        }
    }//GEN-LAST:event_tbl_ventasMouseClicked

    private void spinner_cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinner_cantidadMouseClicked

    }//GEN-LAST:event_spinner_cantidadMouseClicked

    private void btn_cancelar_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_ventasActionPerformed
        op.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelar_ventasActionPerformed

    private void spinner_cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_cantidadStateChanged
        if (seleccionado != null) {
            txtTotal.setText("$" + new DecimalFormat("##.##").format((seleccionado.getPrecio() * (int) spinner_cantidad.getModel().getValue())));
        }
    }//GEN-LAST:event_spinner_cantidadStateChanged
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/ventas.png"));


        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar_ventas;
    private javax.swing.JButton btn_comprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JSpinner spinner_cantidad;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tbl_ventas;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
